# Generated by Django 4.1.7 on 2023-03-18 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_mealimage_meal_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='image',
            new_name='mealimage',
        ),
        migrations.RenameField(
            model_name='mealimage',
            old_name='image',
            new_name='mealimage',
        ),
    ]
