# Generated by Django 4.1.7 on 2023-03-18 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0005_alter_meal_mealimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='mealimage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='meal.mealimage'),
        ),
    ]
