# Generated by Django 4.1.7 on 2023-03-18 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0006_alter_meal_mealimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='mealimage',
        ),
        migrations.AddField(
            model_name='mealimage',
            name='meal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='meal.meal'),
            preserve_default=False,
        ),
    ]
