# Generated by Django 4.1.7 on 2023-03-18 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0007_remove_meal_mealimage_mealimage_meal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealimage',
            old_name='mealimage',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='mealimage',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='meal.meal'),
        ),
    ]
