# Generated by Django 4.1.7 on 2023-03-18 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0008_rename_mealimage_mealimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meal.meal'),
        ),
    ]
