# Generated by Django 4.1.7 on 2023-03-18 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0010_alter_recipe_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='meal',
        ),
        migrations.AddField(
            model_name='meal',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meal.recipe'),
        ),
    ]
